version: '3'

services:
  web:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8093:80
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/php/composer.json:/var/www/html/composer.json
      - ./docker/php/composer.lock:/var/www/html/composer.lock
      - .env:/var/www/html/.env
      - ./readme.md:/var/www/html/readme.md
    expose:
      - 9000
    env_file:
      - .env

  mariadb:
      image: mariadb:10.9
      ports:
        - 3306:3306
      volumes:
        - ./docker/mariadb/database:/var/lib/mysql
        - ./docker/mariadb/dump:/var/backups:rw
      env_file:
        - .env