version: '3'

services:
  web:
    # image: nginx:alpine
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8093:80
    depends_on:
      - app

  app:
    # user: '1000:1000'
    volumes:
      - ./src:/var/www/html:rw
      # - ./docker/sqlite/database.db:/var/www/html/database.db
    # command: bash -c 'chmod 764 /var/www/html/database.db'
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000