version: '3'

services:
  web:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8093:80
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/sqlite/database.db:/var/www/db/database.db
    expose:
      - 9000